name: Daily Commit Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Scheduled daily run at 00:00 UTC
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make changes and commit
        run: |
          echo "Automated commit at $(date)" >> last_run.txt
          git config --local user.name "Flibon"
          git config --local user.email "manavsingh234567@gmail.com"
          git add last_run.txt
          git commit -m "Automated daily commit at $(date)" || true
          git push origin main
